server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  messages:
    basename: messages

  security:
    user:
      name: username
      password: passw0rd